### ISSUE TITLE
Investigate removal of custom math/*Matrix;

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#104]
There is a huge ammount of code in `math/*Matrix` that is old, unmaintained and quite untested. Propose removal and replacement : 

- replace with Connections
- or Eigen #42  
- or keep only the SparseBinaryMatrix

Look at the problem and proposed order of progress: 

`grep -R 'Matrix' src/nupic/math/ | cut -d: -f1 |sort -u`
- [ ] src/nupic/math/Math.hpp 
- [ ] src/nupic/math/ArrayAlgo.hpp -- maybe most of its methods will be removed? 
- [ ] src/nupic/math/DenseMatrix.hpp -- only one user SDRClassifier, replace with sparse & rm first #170  #169 
- [x] src/nupic/math/NearestNeighbor.hpp -- NN does not have to be in a HTM codebase
- [ ] src/nupic/math/SparseBinaryMatrix.hpp -- heavily used in SP #93 , #169 
- [x] algorithms/CondProbTable -- rm too? Uses:
  - [x] src/nupic/math/SparseMatrix01.hpp -- not used, rm
- [ ] src/nupic/math/SparseMatrix.hpp -- huge, untested, suprisingly not a base of SparseBinaryM #169 
  - used in ArrayAlgo, DenseMatrix, SpatialPooler
- [x] src/nupic/math/SparseMatrixAlgorithms.hpp -- not used, rm
- [x] src/nupic/math/SparseMatrixConnections.hpp -- not used, rm
  - [x] src/nupic/math/SegmentMatrixAdapter.hpp -- used only in SMConn
    - [x] py_SegmentSparseMatrix
- [x] src/nupic/math/SparseRLEMatrix.hpp -- not used, rm
- [ ] src/nupic/math/SparseTensor.hpp -- not sure how needed for Py  - implemented (but reverted) here:  bfb58df  , #169 
  - [ ] Domain
  - [ ] Index
  - [ ] PyBindSparseTensor 
- [x] math/Math.hpp:Gaussian_2D -- not used, further cleanup Math.hpp

Related:
 - #93 SP on Connections

Prerequisities: 
 - [ ] c++ speed tests #30 
 - [ ] validate Python nupic still compatible with this nupic.core #137

**Comment by dkeeney** [comment]
Hmmm, if that is exposed to Python code it might be used more than you think.

**Comment by breznak** [comment]
> f that is exposed to Python code it might be used more than you think. 

Good call, but no. SparseMatrix is used everywhere, Dense only in that one class. 
I'd like to:
- rid off Dense
- (optionally) replace Sparse with Eigen::SparseMatrix

**Comment by dkeeney** [comment]
> - rid off Dense

Yes.
> - (optionally) replace Sparse with Eigen::SparseMatrix

Don't know enough about Eigen to tell you if it is a good idea.

**Comment by breznak** [comment]
Reopening to continue further cleanup after #93 
Next target:  bfb58df

**Comment by breznak** [comment]
I will try to resume this work and rm further more, given #153 is merged now.
