### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#47]
@dkeeney @chhenning  I was reviewing your interesting work on refactoring/reducing nupic.core, and I'd like to get it merged back here to some extend. 

Features that I like: 
- [ ] using c++ instead of boost, where possible. Seen in @dkeeney 's `base` branch? ~~Although I'm interested only in changes with c++11 (not ++17 as you target)~~ Ok, let's go c++17. #55 #106 
- [x] removing apr* , boost.filesystem is the replacement? Also in the base branch?  #74 
- [x] getting rid of zlib / capnp for compression. I think one of you sticks with either. I'd for sure remove zlib, as users can zip themselves; ~~capnp adds lots of mess, but works quite ok, do you think vanilla plain-text backups are ok/better?~~ #48 
- [x] removing Swig, replacing with pybind11 (@chhenning  ?) does it work well? which branch can I start cherry-picking and merging from? Or David has gone the pure C++ way. 
...this bullet will be quite complex, I'll leave it for now for further discussion.  #81 
  - [ ] Do I still need/benefit from your SP/TMRegion classes? #54

**Comment by dkeeney** [comment]
I would rather not require boost.  With c++17 we get most of what boost
provides as std::, including filesystem.  I think most people now have
compilers that can support c++17.

Zlib was used only as an alternative way to feed data to one of the
encoders. Not part of serialization.  By removing that one minor feature we
can reduce the dependencies.

capnp is a real pain to follow and maintain. @chhenning and I want to
replace it. Nobody else had any comment.

Yes, replace Swig with pybind11 but all of that code will be in another
repository.  One that calls the pure C++ library. The code should be much
easier to maintain as separate repositories.  @chhenning was working on
that but got bogged down in his real job.

Without the SP/TMRegion classes it is impossible to write any NPIC
implementations using the Network Framework in C++ only. The CSharp
language interface will also need this because it would have a hard time
calling Python to get to the SP/TMRegion modules.  So it makes since to
fill in the missing parts in the C++ library.

**Comment by breznak** [comment]
I like to notion about zlib and capnp, I'll join that! I'll have to think about cpp17 and completely pure c++, but I agree it's the cleanest solution...so when the time comes. 
Actually, is anybody else developing the repos?

**Comment by dkeeney** [comment]
There are a lot of people doing there own thing.  But as far as I know,
you, I and @chhenning are the only one's doing anything with nupic.cpp.

I suspect that some people have looked at the current Nupic implementation
as a starting point for their implementations and just decided to roll
there own because it would be simpler.  So one of my objectives is to make
a simple implementation (within the API) that can be understood by looking
at the code and ... something that uses the latest technology.

By using C++17 we can avoid boost.  I would rather be on the leading edge
of technology that lagging behind (like requiring python2.7 and a very old
compiler that matches).

**Comment by chhenning** [comment]
Sorry for the late reply. Welcome back breznak! My pybind (replacement for swig) bindinds are working very well, I think. Have a look here:

https://github.com/chhenning/nupic/tree/master/src/cpp/nupic/python

**Comment by dkeeney** [comment]
@breznak, shall we put in pybind and isolate the python interface now or are there other smaller components you would like to put in first?  I am trying to decide what part to do next.

**Comment by breznak** [comment]
Updated the description with decision based on your advices, added links to respective issues. 

@dkeeney I think pybind is rather a big step, for now I'd like to align as much as possible with yours and Christian's work..so smaller pieces first, please. 

1. ASAP merge #52 (please answer comments), and finish and merge #46 
2. serialization #48 
3. c++17 in #55
4. Region classes (should be relatively independent) #54

**Comment by dkeeney** [comment]
I guess the next project is to remove capnproto.   #48 
I will take that one unless someone has already started it.

**Comment by breznak** [comment]
that'll be perfect and a big cleanup!

**Comment by breznak** [comment]
With #169 we'll have most of boost includes removed, 
only remaining are 
- [ ] math/ArrayAlgo.hpp
- [ ] math/Math.hpp

and I'm working on those. 

@dkeeney can we revisit switch to c++17 #55 and then proceed with this one?

**Comment by breznak** [comment]
Closing and moving to #106 as the only remaining part of this issue.
